### ISSUE TITLE
Text contents erased when window is resized

### ISSUE THREAD

**Issue by samo79** [sodero/MUI-Vim#10]
Noted that the text content of the window will just disappear when user will start resizing the window.
For example see this kas1e video (at second 0:18)

https://m.youtube.com/watch?v=UBOuVuGUTZ0&t=283s

**Comment by sodero** [comment]
That's expected behavior (it behaves the same way on other platforms),  the welcome message disappears as soon as there's user input, keyboard or mouse etc.
