### ISSUE TITLE
Installer stopped when adding "egVIM"

### ISSUE THREAD

**Issue by samo79** [sodero/MUI-Vim#11]
Just reinstalled latest VIM from scratch and noted that if i add "egVIM" from the list of things to install, i got a couple of errors:

COPYFILES: No prompt specified at line 129.
COPYFILES: No help text specified at line 129.

**Comment by sodero** [comment]
I think I fixed this but I have no way of verifying that it works with the OS4 installer. Does the latest build work for you?

**Comment by samo79** [comment]
Yes it's fixed, just installed and now all goes well
You can close the ticket

**Comment by sodero** [comment]
Nice!
