### ISSUE TITLE
[AROS] Crash at exit

### ISSUE THREAD

**Issue by deadw00d** [sodero/MUI-Vim#15]
Hi,

The line below is causing crash on AROS hosted i386. The _win() macro requires existance of MUI_AreaData and MUI_RenderInfo which are available only in subclasses of Area class, while here it is called on Application class. Note: I don't know if this works on other systems or just silently fails or if this is AROS incompatibily (?)

https://github.com/sodero/MUI-Vim/blob/d5c0150f91db292e769ba500703c5bfe45e921e6/src/gui_mui.c#L3537

**Comment by sodero** [comment]
Hi!

Thanks for reporting this. It works on MOS, OS4 and Icaros but perhaps it shouldn't, I'm not sure.

Does it work if you replace _win(App) with _win(Con)?

**Comment by sodero** [comment]
Let's hope it works, https://github.com/sodero/MUI-Vim/commit/6aca22195e98b82c24cda09cbc878007b950ad27

I don't have access to all the machinery needed to do a new release right now but I'll try to upload a new release to Aminet tomorrow.

**Comment by deadw00d** [comment]
The 8.2.4370 from Aminet no longer crashes at exit for me

**Comment by sodero** [comment]
Nice.
