### ISSUE TITLE
Release outdated

### ISSUE THREAD

**Issue by mattrust** [sodero/MUI-Vim#16]
The most recent release is 8.2.4291. It has the crash-on-exit bug on AROS.
Would you please add a fixed version to the release page?

AROS' build system has options to fetch and build from external sources.
https://github.com/aros-development-team/ports/tree/master/text/vim
That's why I need a source release with the fix.

**Comment by sodero** [comment]
Done. I haven't checked if there are any missing files in the mmakefile.src but if so you can just compare it with src/Make_ami.mak.
